// GET CALL
export const API_REQUEST = "GET_CONTRACT_REQUEST";
export const API_FAILURE = "GET_CONTRACT_FAILURE";
export const CLOSE_FORM = "CLOSE_FORM";
export const OPEN_FORM = "OPEN_FORM";
export const CLEAR_FORM = "CLEAR_FORM";

// contract api 
export const GET_CONTRACT_SUCCESS = "GET_CONTRACT_SUCCESS";
export const POST_CONTRACT_SUCCESS = "POST_CONTRACT_SUCCESS";
export const DELETE_CONTRACT_SUCCESS = "DELETE_CONTRACT_SUCCESS";
export const EDIT_CONTRACT_SUCCESS = "EDIT_CONTRACT_SUCCESS";
export const GET_CONTRACT_BY_ID = "GET_CONTRACT_BY_ID";

// service api
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const POST_SERVICE_SUCCESS = "POST_SERVICE_SUCCESS";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const EDIT_SERVICE_SUCCESS = "EDIT_SERVICE_SUCCESS";
export const GET_SERVICE_BY_ID = "GET_SERVICE_BY_ID";

// mapping api
export const GET_MAPPING_SUCCESS = "GET_MAPPING_SUCCESS";
export const POST_MAPPING_SUCCESS = "POST_MAPPING_SUCCESS";
export const DELETE_MAPPING_SUCCESS = "DELETE_MAPPING_SUCCESS";
export const EDIT_MAPPINGSUCCESS = "EDIT_MAPPING_SUCCESS";
export const GET_MAPPING_BY_ID = "GET_MAPPING_BY_ID";



